.\"
.\" Copyright (C) 2004 International Business Machines
.\" Nathan Fontenot <nfont@austin.ibm.com>
.\"
.TH BOOTLIST 8 "April 2004" Linux "Linux on Power Service Tools"
.SH NAME
bootlist - update and view the bootlist
.SH SYNOPSIS
.nf
\fB/usr/sbin/bootlist \-m normal\fR|\fBservice\fR|\fBboth \fR[\fB-o\fR|\fB-r\fR] <\fIdev_list\fR>
\fB/usr/sbin/bootlist \-m normal\fR|\fBservice\fR|\fBboth \fR[\fB-o\fR|\fB-r\fR] \fB-f \fIfile
.fi
.SH DESCRIPTION
The bootlist command allows users to view and update the system bootlist
stored in NVRAM for PowerPC-64 machines.  The bootlist entries can be
specified as either logical device names or Open Firmware device path names.
The bootlist will convert all names to Open Firmware device path names using
\fIofpathname\fR when updating the bootlist.  Then uses the \fInvram\fR
command to update NVRAM.  If a list of devices is specified, the boot list
will be updated with the list provided.  If a list is not specified, the
current boot list will be printed.
.SH OPTIONS
.TP
\fB\-m normal\fR|\fBservice\fR|\fBboth
Required; specify whether the normal or service mode boot list should be
viewed/updated.  Specifying "both" will update the normal and service mode
boot lists.
.TP
\fB\-o
Display the current boot list entries as logical device names.
.TP
\fB\-r
Display the current boot list entries as Open Firmware device path names
(default).
.TP
\fB\-f \fIfile
Read the bootlist device names from \fIfile\fR, one entry per line.
.TP
\fIdev_list
A space-separated list of devices, specified as logical device names or OF
device path names, depending on whether the \fB-o\fR or \fB-r\fR option is
specified.
.SH EXAMPLES
.nf
View the normal mode boot list as logical device names:

    /usr/sbin/bootlist -o -m normal

Update the service mode boot list:

    /usr/sbin/bootlist -o -m service /dev/sda3 /dev/cdrom
.fi
.SH AUTHOR
Written by Nathan Fontenot
.SH "SEE ALSO"
.BR ofpathname (8),
.BR nvram (8)


