.\"
.\" Copyright (C) 2004 International Business Machines
.\" Michael Strosaker <strosake@us.ibm.com>
.\"
.TH USYSATTN 8 "May 2004" Linux "Linux on Power Service Tools"
.SH NAME
usysattn \- turn off system attention indicators
.SH SYNOPSIS
.nf
\fB/usr/sbin/usysattn [\-l \fIlocation_code\fB] [\-s normal]
\fB/usr/sbin/usysfault [\-l \fIlocation_code\fB] [\-s normal]
.fi
.SH DESCRIPTION
.P
The \fIusysattn\fR utility is used to view and manipulate the attention
indicators (LEDs) on PowerPC-64 machines.  These indicators are turned on
automatically when a serviceable event is received.  These identifiers are
specified by location code.

.P
When run without arguments, \fIusysattn\fR will print a list of all of the
attention indicators on the system along with their current status (on or
off).  The \fB\-l\fR option can be used to specify a particular indicator.
If \fB\-l\fR is the only argument, the status of that indicator will be
printed.  If \fB\-s\fR \fInormal\fR is specified along with the \fB\-l\fR
argument, the indicator will be turned off.

.P
.B NOTE:
Ensure that there are no outstanding service actions to be taken on this
system before turning off the system attention indicators. 
.SH OPTIONS
.TP
\fB\-l \fIlocation_code
Specify the location code of the indicator.
.TP
\fB\-s normal
Must be used with the \fB\-l\fR option; turns the specified indicator off.

.SH "SEE ALSO"
.BR usysident (8)
