#! /bin/bash

# Copyright (c) 2010 International Business Machines
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# Author Brian King <brking@linux.vnet.ibm.com>
#
# ls-veth - This utility provides the HMC or IVM with name information for
# 	    virtual ethernet devices
#

LSVETH="ls-veth"
VERSION="0.1"
OFPATHNAME="/usr/sbin/ofpathname"
CAT="/bin/cat"
LS="/bin/ls"
SED="/bin/sed"
PSERIES_PLATFORM=$(dirname $0)/pseries_platform

usage()
{
    echo "Usage: $LSVETH "
    echo "Provide information on Virtual Ethernet devices"
    echo ""
    echo "Optional arguments."
    echo "  -V	Display version information and exit"
    echo "  -h	Display this help information and exit"
    echo ""
}

show_version()
{
    echo "$LSVETH: Version $VERSION"
    echo "Written by: Brian King <brking@linux.vnet.ibm.com>"
}

. $PSERIES_PLATFORM
if [[ $platform != $PLATFORM_PSERIES_LPAR ]]; then
      echo "$LSVETH: is not supported on the $platform_name platform"
      exit 1
fi

while getopts ":Vh" flag ; do
    case "$flag" in
        V) show_version
                        exit 0 ;;

        h)              usage
                        exit 0 ;;
        \?)             usage
                        exit 1 ;;
    esac
done

# Look at every ibmveth (Virtual Ethernet) device
for dev in $($LS -d /proc/device-tree/vdevice/l-lan* 2> /dev/null); do
    # use ofpathname to get the device name (i.e. eth0)
    name=$($OFPATHNAME -l $(echo $dev | $SED -e "s/\/proc\/device-tree//"))

    # get the physical location
    physloc=$(tr -d '\0' < $dev/ibm,loc-code)

    echo "$name $physloc"
done

exit 0

# end
