#!/bin/sh

# Copyright (c) 2014 - IBM
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

SOURCE_FILE="pseries_platform"
PLATFORM_FILE=/proc/cpuinfo
export PLATFORM_UNKNOWN=0
export PLATFORM_POWERNV=1
export PLATFORM_POWERKVM_GUEST=2
export PLATFORM_PSERIES_LPAR=3

export platform_name="Unknown"
export platform=$PLATFORM_UNKNOWN

if grep -q "PowerNV" $PLATFORM_FILE; then
	platform_name="PowerNV Host"
	platform=$PLATFORM_POWERNV
elif grep -q "IBM pSeries (emulated by qemu)" $PLATFORM_FILE; then
	platform_name="Power KVM pSeries Guest"
	platform=$PLATFORM_POWERKVM_GUEST
elif  grep -q "pSeries" $PLATFORM_FILE; then
	platform_name="PowerVM pSeries LPAR"
	platform=$PLATFORM_PSERIES_LPAR
fi

if [ $SOURCE_FILE = `basename $0` ]; then
	echo $platform_name
fi
